version: "3"

services:
  node:
    image: node:16.14-slim
    container_name: trybeteca_api
    command: npm run dev
    working_dir: /app
    # Usuário linux padrão do container, não é recomendado usar root
    # https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user
    user: node
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: trybeteca_db
      DB_PORT: 3306
      JWT_SECRET: secret

  db:
    container_name: trybeteca_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
